services:
  backend:
    image: backend
    build: ./server
    ports:
      - "5001:5001"

  #frontend:
  #  image: frontend
  #  build: ./client
  #  ports:
  #    - "3000:3000"

  panns:
    image: panns
    build: ./ml
    ports:
      - "5002:5002"

  listener:
    image: listener
    build: ./scripts
    devices:
      - "/dev/snd:/dev/snd"
    ports:
      - "8080:8080"